force-app/main/default/objects/Mobile__c/Mobile__c.object-meta.xml
<CustomObject>
    <label>Mobile</label>
    <nameField>
        <label>Mobile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mobile__c/fields/MRP__c.field-meta.xml
<CustomField>
    <fullName>MRP__c</fullName>
    <label>MRP</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Mobile__c/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <label>Picture_URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Mobile__c/fields/Series__c.field-meta.xml
<CustomField>
    <fullName>Series__c</fullName>
    <label>Series</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>Asus</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Oneplus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MobileController.cls
public with sharing class MobileController {
    //wrapper class
    public class Filters{
        @AuraEnabled
        public String searchKey{get;set;}
        @AuraEnabled
        public Decimal maxPrice{get;set;}
        @AuraEnabled
        public String[] series{get;set;}
    }
    @AuraEnabled(Cacheable=true)
    public static List<Mobile__c> getMobiles(Filters filters) {
        String key, whereClause = '';
        Decimal maxPrice;
        String[] series, criteria = new List<String>{};
        if(filters != null) {
            maxPrice = filters.maxPrice;
            series = filters.series;
            if(!String.isEmpty(filters.searchKey)){
                key = '%' + filters.searchKey + '%';
                criteria.add('Name LIKE: key');
            }
            if(filters.maxPrice >= 0){
                criteria.add('MRP__c <= :maxPrice');
            }
            if(filters.series != null){
                criteria.add('Series__c IN :series');
            }
            if(criteria.size() > 0){
                whereClause = 'WHERE ' + String.join(criteria, ' AND ');
            }
        }

        String query = 'SELECT Id, Name, MRP__c, Series__c, Description__c, Picture_URL__c FROM Mobile__c ' + whereClause + ' WITH SECURITY_ENFORCED ORDER BY Name';
        return Database.query(query);

    }

}